### ISSUE TITLE
my project messy with new update

### ISSUE THREAD

**Issue by abehbatre** [fluttercandies/FlutterJsonBeanFactory#103]
![image](https://user-images.githubusercontent.com/36602270/142846586-ed24a800-5ec3-4cfe-b813-93d95d013ea3.png)

whats happen? why???

**Comment by zhangruiyu** [comment]
It's not a good way to use “with”. At that time, I was just learning about Flutter. The new version of Flutter is modeled after the official JSON plugin. It will be more helpful for adding more functions in the future. Of course the inevitable user will update something, sorry about that
