### ISSUE TITLE
建议readme添加一下break change说明

### ISSUE THREAD

**Issue by pakeng** [fluttercandies/FlutterJsonBeanFactory#104]
建议添加一下 break change的说明；

由于修改了实现方式，导致我们的工程出现大量的修改工作，如果有一个说明或许我们可以选择在必要的时候进行更新，而不是直接更新，然后再处理混乱的情况，甚至当出现了问题之后我都怀疑是我的操作方法不对。

建议添加一下说明。

当然插件是一个很优秀的插件，感谢大佬～！

**Comment by zhangruiyu** [comment]
真的抱歉,总归是不破不立,其实我已经插件里添加了对以前的修改,我自己app其实也就修改了不到10处,基本就是去把某些 xxxentity().fromjson里去掉,

**Comment by pakeng** [comment]
> 
大佬：
抱歉说不上啊，确实是不破不立，再次感谢大佬的产出！
