### ISSUE TITLE
报错dynamic not found怎么解决

### ISSUE THREAD

**Issue by HiMsszhang** [fluttercandies/FlutterJsonBeanFactory#107]
![截屏2022-01-10 16 34 35](https://user-images.githubusercontent.com/49504344/148737347-ad90113f-5e42-410e-b075-38429dd875f3.png)

1. ` var res = await HttpManager.getInstance().post('/app/login', context: context, params: params);
    LoginDataEntity model = JsonConvert.fromJsonAsT(res);

    return model;`

**Comment by zhangruiyu** [comment]
那你为啥不传泛型呢
