### ISSUE TITLE
不能生成generated目录以及目录下的辅助类

### ISSUE THREAD

**Issue by shanerou** [fluttercandies/FlutterJsonBeanFactory#108]
android studio Arctic Fox | 2020.3.1版本
使用时提示as提示：
No classes that inherit JsonConvert were found,the project root directory must contain the lib directory, because this plugin will only scan the lib directory of the root directory

不能生成generated目录以及目录下的辅助类，删除.idea文件重启也不行

**Comment by shanerou** [comment]
FlutterJsonBeanFactory版本4.3.2

**Comment by zhangruiyu** [comment]
删除.idea目录,并且
![image](https://user-images.githubusercontent.com/10591822/149855823-6657452d-0be2-40a7-af41-01c494712a3d.png)
然后重启as
