### ISSUE TITLE
某个字段为null，生成JSON时，可否设置忽略该字段

### ISSUE THREAD

**Issue by shitb** [fluttercandies/FlutterJsonBeanFactory#109]
某个字段为null，生成JSON时，可否设置忽略该字段

**Comment by zhangruiyu** [comment]
删了不就可以

**Comment by shitb** [comment]
> 删了不就可以

如果该字段有值，生成Json时还想保留该字段，如果为null时，生成JSON时，想去除该字段

**Comment by zhangruiyu** [comment]
意义不是很大

**Comment by zhangruiyu** [comment]
可以自己fork改

**Comment by shitb** [comment]
> 

对不起，我只会CV

**Comment by shitb** [comment]
> 可以自己fork改

对不起，我是CV攻城狮

**Comment by zhangruiyu** [comment]
因为不是什么大问题的东西，我觉得不用处理

**Comment by shitb** [comment]
> 因为不是什么大问题的东西，我觉得不用处理

恩，另找个方式解决了，官方里边有个 includeIfNull,  属于锦上添加的东西。
