### ISSUE TITLE
不自动生成generated文件及下面的辅助类

### ISSUE THREAD

**Issue by zhukai-cn** [fluttercandies/FlutterJsonBeanFactory#111]
集成了插件后，会生成dart类，但不自动生成generated文件及下面的辅助类，我观察到应该是插件没有获取到我的包名路径，我有对flutter模块的项目名和name进行过修改。请问这个问题怎么解决？
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/20353386/159622573-f6fb2410-e0b9-43e8-9380-95efe6efcd4b.png">

**Comment by zhangruiyu** [comment]
插件更新到最新包
