### ISSUE TITLE
关于json_convert_content不断膨胀的一个建议

### ISSUE THREAD

**Issue by luooyii** [fluttercandies/FlutterJsonBeanFactory#112]
Hi 作者,

目前的json_convert_content在生成新对象的时候不断膨胀，也许可以考虑用函数式的方式避免这个问题

只需要把Entity.fromJson作为参数传入，就可以通过递归的方式解析json，从而避免content类膨胀。
如：List<Bin>? binList = JsonConvertUtils.convertListNotNull<Bin>(pagination.results, convert: Bin.fromJson);

![image](https://user-images.githubusercontent.com/20371202/161383859-407601bc-1c4b-40a9-93d8-7086ebdb7718.png)

如果按这样修改，考虑兼容性的问题，可以这样改造生成结构。只需要在新的实体类完全用新的convert就不存在兼容性问题。
```
--generated
  --json
    --base
      --json_convert_utils.dart（新）
      --json_convert_content.dart（旧）
      --json_field.dart
```

还有一个建议，希望将实体文件和.g文件放在同级目录下，这样的话想删除某个模块的东西就可以直接删掉父目录。不需要再跑到根目录generated目录下再删.g文件。
```
--lib
  --moduleA
    --entity
       --entityA.dart
    --generated
       --entityA.g.dart
```

**Comment by zhangruiyu** [comment]
1. 可以考虑 我今天试试
2. 不好 你删掉后 只需要重新按下快捷键对应的.g也会自动删除

**Comment by zhangruiyu** [comment]
第一个 目前不知道怎么解决fromJsonAsT在网络请求里通过泛型实例化的优化

**Comment by zhangruiyu** [comment]
如果你有什么好办法可以加群 963752388

**Comment by zhangruiyu** [comment]
新版本发布了 用map存放的
