### ISSUE TITLE
all generated files got deleted

### ISSUE THREAD

**Issue by mueksh-b** [fluttercandies/FlutterJsonBeanFactory#113]
After updating the plugin to the latest version all generated files got deleted from "json" folder

**Comment by zhangruiyu** [comment]
![image](https://user-images.githubusercontent.com/10591822/162374940-6f390461-21d1-4cbc-ba7f-b412995d575b.png)
Try pressing the shortcut key

**Comment by zhangruiyu** [comment]
version 4.3.5 has been fixed
