### ISSUE TITLE
package:null/generated/json/base/json_field.dart

### ISSUE THREAD

**Issue by lpfasd123** [fluttercandies/FlutterJsonBeanFactory#117]
没有自动生成generated文件夹，在生成的实体类中显示import 'package:null/generated/json/base/json_field.dart';
import 'package:null/generated/json/cases_model.g.dart'
![截屏2022-05-11 下午2 58 53](https://user-images.githubusercontent.com/18106385/167788238-79e6c6bb-2a96-4f0d-a1ee-f48b7f9fd0e6.png)
;

**Comment by zhangruiyu** [comment]
清理下as缓存

**Comment by lpfasd123** [comment]
![截屏2022-05-13 下午1 36 39](https://user-images.githubusercontent.com/18106385/168218031-d55fa1c3-06d3-4e80-beee-fc97c3c1058e.png)
清理缓存之后，依然无效

**Comment by wlwoon** [comment]
@lpfasd123 大佬 怎么解决的  我也遇到了
