### ISSUE TITLE
从eventStream返回的event中,字典为Map<dynamic,dynamic>，其嵌套的Map<Object?,Object?>导致解析不了

### ISSUE THREAD

**Issue by bestoml** [fluttercandies/FlutterJsonBeanFactory#126]
我们这边从原生返回的为字典,直接解析不了，因为类型不对，于是我们在外层转换了一下：
final event3 = Map<String, dynamic>.from(event);
DeviceModelEntity device = DeviceModelEntity.fromJson(event3);
这样，外层的解析就正确了，但是嵌套层没有解析出来。跟踪代码来到：json_convert_content.dart
if (_convertFuncMap.containsKey(type)) {
          value = Map<String, dynamic>.from(value); //added to convert type
          return _convertFuncMap[type]!(value) as T;
        } else {
原因在于内层嵌套中的类型为Map<Object?,Object?>，于是解析走不下去了。
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/5017099/194806805-b653c922-91e5-40cd-b7fb-962ad4e550e7.png">

总结建议：
1.外层生成的fromJson，参数建议改为Map<dynamic,dynamic>，这样外层不需要显示转换，判断可以放在内层；
2.内层嵌套，建议像上面一样加入类型转换。

**Comment by zhangruiyu** [comment]
已修复
