### ISSUE TITLE
希望可以增加生成文件目录的配置

### ISSUE THREAD

**Issue by cr1992** [fluttercandies/FlutterJsonBeanFactory#127]
如题，目前生成的文件只能在lib目录下的generated目录，希望可以提供配置能力

**Comment by cr1992** [comment]
> 说实话不是很明白这个需求的意义

<img width="219" alt="image" src="https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/14345890/8146024b-4f7c-4500-ba1c-2e5d4b7ad2f0">

项目中有src目录，因为插件生成的文件目录不支持配置所以现在的目录结构是这样的

**Comment by zhangruiyu** [comment]
明白了  我会做这个需求的 但是麻烦请等等

**Comment by zhangruiyu** [comment]
理解意思我就知道咋搞了

**Comment by zhangruiyu** [comment]
这个配置项写到yaml文件里你觉得咋样

**Comment by cr1992** [comment]
> 这个配置项写到yaml文件里你觉得咋样

蛮好的，可以根据module配置

**Comment by zhangruiyu** [comment]
已经做了,发布了,可以升级到5.0.0-beta_1
如果可以,我想无耻的说一句,能请我喝瓶无糖可乐吗
![8c9d200d73bd290130908e00df4061ea](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/10591822/498e9a91-feaa-4557-8153-195092f3208b)

**Comment by zhangruiyu** [comment]
emmm 看到你直接关闭 甚至回复也没 其实还是有点难受的 维护这个确实占用了大量时间  之前我也没贴过二维码  
甚至没有收到过什么鼓励 对我找工作也没有帮助 确实迷茫了

**Comment by cr1992** [comment]
> emmm 看到你直接关闭 甚至回复也没 其实还是有点难受的 维护这个确实占用了大量时间 之前我也没贴过二维码 甚至没有收到过什么鼓励 对我找工作也没有帮助 确实迷茫了

啊这，其实已经有给你打了一小比钱了哦👀，项目做的很棒，我们这边一直在用

**Comment by cr1992** [comment]
> emmm 看到你直接关闭 甚至回复也没 其实还是有点难受的 维护这个确实占用了大量时间 之前我也没贴过二维码 甚至没有收到过什么鼓励 对我找工作也没有帮助 确实迷茫了

加油加油，希望你工作蒸蒸日上

**Comment by zhangruiyu** [comment]
> > emmm 看到你直接关闭 甚至回复也没 其实还是有点难受的 维护这个确实占用了大量时间 之前我也没贴过二维码 甚至没有收到过什么鼓励 对我找工作也没有帮助 确实迷茫了
> 
> 加油加油，希望你工作蒸蒸日上

😂真的是谢谢你，哎，感觉生活太累了，今天一天没干活就搞这个了，实在有点都不太想维护了。真心的感谢
