### ISSUE TITLE
不同模块bean在List解析不到

### ISSUE THREAD

**Issue by ctluocc** [fluttercandies/FlutterJsonBeanFactory#133]
### Platforms

dart

### Description

主工程有依赖了不同的模块，每个模块有对应的对象,会生成不同的json_conver_content.dart。发现convertFuncMap可以把不同模块的map加起来能解析，但是List没法通用解析，希望可以支持串联不同模块，可以通用解析。

**Comment by zhangruiyu** [comment]
我的建议是这个模块单独用项目形式打开 然后在里面生成json_conver_content,这样主项目可以导包这个
