### ISSUE TITLE
升级新版之后，不支持List<List>结构

### ISSUE THREAD

**Issue by Icyoung** [fluttercandies/FlutterJsonBeanFactory#135]
### Content

每次生成我都需要在 _asT函数中补上，希望尽快修复
else if(type == 'List' || type.startsWith('List<')) {
			return value as T;
		} else if (type == 'dynamic') {
			return value as T;
		}

**Comment by zhangruiyu** [comment]
请给出具体代码，例子，给我来个例子链接

**Comment by Icyoung** [comment]
{
    "a":[
        [
            "1",
            "2",
            "3"
        ],
        [
            "3",
            "4",
            "5"
        ],
        [
            "6",
            "7",
            "8"
        ]
    ],
    "b":[
        [
            "9",
            "10",
            "11"
        ],
        [
            "12",
            "13",
            "14"
        ],
        [
            "15",
            "16",
            "17"
        ]
    ]
}

**Comment by zhangruiyu** [comment]
写dynamic吧

**Comment by zhangruiyu** [comment]
或者忽略这个字段的解析，重写tojson fromjson方法，别卸载.g文件里

**Comment by zhangruiyu** [comment]
或者忽略这个字段的解析，重写tojson fromjson方法，别写在.g文件里

**Comment by Icyoung** [comment]
重写序列化方法倒是可以，不过在 _asT中增加逻辑对List的解析好像没啥问题，甚至还可以递归convertList，不过要兼容可空的话可能需要正则来判断

**Comment by zhangruiyu** [comment]
现在支持了
