### ISSUE TITLE
4.5.0版本不支持map？

### ISSUE THREAD

**Issue by JDongKhan** [fluttercandies/FlutterJsonBeanFactory#136]
### Platforms

Android, iOS

### Description

您好，我在使用最新版本4.5.0的时候，在类里面定义了一个
```dart
Map<String, DataDetailSugarInfoEightGroupSugarMap>? sugarMap;，
```
key是string，value是一个对象，看到里面的_asT里面的代码在处理map的时候直接是 

```dart
else if (type == "Map" || type.startsWith("Map<")) {
      return value as T;
    } 
```

这样强转，直接异常了，插件不支持这个能力吗？

还是需要什么额外的配置？
### My code

@JsonSerializable()
class DataDetailSugarInfoEightGroup {
  String? dataDayStr;
  Map<String, DataDetailSugarInfoEightGroupSugarMap>? sugarMap;

  DataDetailSugarInfoEightGroup();

  factory DataDetailSugarInfoEightGroup.fromJson(Map<String, dynamic> json) =>
      $DataDetailSugarInfoEightGroupFromJson(json);

  Map<String, dynamic> toJson() => $DataDetailSugarInfoEightGroupToJson(this);

  @override
  String toString() {
    return jsonEncode(this);
  }
}

**Comment by JDongKhan** [comment]
![1](https://user-images.githubusercontent.com/4929805/233272233-97c3c811-d792-4b6f-b7e2-8d592261c53a.png)
![2](https://user-images.githubusercontent.com/4929805/233272249-569a27a1-aebc-486e-ad04-ee53108a4eae.png)

**Comment by zhangruiyu** [comment]
额 暂不支持 你可以写dynamic或者var

**Comment by zhangruiyu** [comment]
后面有考虑加 但是最近木啥时间搞这个

**Comment by JDongKhan** [comment]
多谢回复，我先忽略这个字段，自己解析吧

**Comment by zhangruiyu** [comment]
现在支持了
