### ISSUE TITLE
创建bean文件失败，提示文件已存在

### ISSUE THREAD

**Issue by Microcrab** [fluttercandies/FlutterJsonBeanFactory#138]
![image](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/17917564/f945d8f3-10d3-4181-9306-f7d2db9a2ae3)
![image](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/17917564/3062d787-dd94-45f6-8404-d39382e4fe94)
![image](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/17917564/a907b1a7-9707-48bf-9c11-35ec1821b948)

问题如图，似乎是因为已经存在了后缀相同的bean文件导致。
麻烦看一下是什么原因？

**Comment by zhangruiyu** [comment]
名字重复了，换个名呗

**Comment by Microcrab** [comment]
> 名字重复了，换个名字呗

如上面的例子，是 favorite_scene_list_req_entity.dart 和 scene_list_req_entity.dart 重名了，好像不太对吧。或者说判断重复的规则是什么？

**Comment by zhangruiyu** [comment]
同项目都不能有相同名字的

**Comment by Microcrab** [comment]
> 同项目目都不能有相同名称的

嗯，我理解完全相同肯定不行，但 favorite_scene_list_req_entity.dart 和 scene_list_req_entity.dart ，差了一个单词，并不重复吧。

**Comment by zhangruiyu** [comment]
可能里面的类名有没有重复呢

**Comment by zhangruiyu** [comment]
或者你加qq群问吧，这里交流有点麻烦

**Comment by zhangruiyu** [comment]
已经修复
