### ISSUE TITLE
[How to use]  我有一个泛型 BaseEntity<T>的问题。应该怎么解析

### ISSUE THREAD

**Issue by wosika** [fluttercandies/FlutterJsonBeanFactory#140]
### Platforms

dart

### Description

我的通用格式是{"code":0 ,"msg":"message",data:xxxx}
data可能是各种类型的数据。我应该怎么做？
<img width="923" alt="image" src="https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/22899955/d238bedd-a994-467d-9251-08b8c21781f6">
如果我用泛型alt+j生成的是报红的。

**Comment by zhangruiyu** [comment]
请看完后自行封装
https://juejin.cn/post/7030739002969817118/
