### ISSUE TITLE
[Discussions] 为什么校验文件是否在文件夹里是使用contains而不是全等比较？

### ISSUE THREAD

**Issue by 404N** [fluttercandies/FlutterJsonBeanFactory#142]
### Content

以下是插件源码
    /**
     * 判断Directory中是否包含这个file
     */
    fun containsDirectoryFile(directory: PsiDirectory, fileName: String): Boolean {
        return directory.files.filter { it.name.endsWith(".dart") }
            .firstOrNull { it.name.contains(fileName) } != null
    }

如果我同一个文件夹中先创建了home_tab_entity，之后就创建不了tab_entity了

**Comment by zhangruiyu** [comment]
好的，我最近会看看这个问题 然后修复的

**Comment by zhangruiyu** [comment]
已经修复了
