### ISSUE TITLE
[Bug report]  List<List<obj>> 这样的结构在4.4.6版本以上解析不了

### ISSUE THREAD

**Issue by yfming93** [fluttercandies/FlutterJsonBeanFactory#143]
### Version

2.5.2

### Platforms

dart

### Device Model

all

### flutter info

```sh
null
```

### How to reproduce?

{
	"data":{
		"list":[
			[
				Obj
			],
			[
				Obj
			],
		]
	}
}

4.4.6以上版本的解析不了如上json结构。List<List<obj>> 在4.4.6以上解析不了

### Logs

```sh
{
	"data":{
		"list":[
			[
				Obj
			],
			[
				Obj
			],
		]
	}
}

4.4.6以上版本的解析不了如上json结构。List<List<obj>> 在4.4.6以上解析不了
```

### Example code (optional)

```Dart
{
	"data":{
		"list":[
			[
				Obj
			],
			[
				Obj
			],
		]
	}
}

4.4.6以上版本的解析不了如上json结构。late List<List<obj>>  = list [] 在4.4.6以上解析不了
```

### Contact

yfmingo@163.com

**Comment by zhangruiyu** [comment]
不支持二维,可以写dynamic

**Comment by yfming93** [comment]
> 不支持二维,可以写dynamic

exchange `late List<List<obj>>  = list []` to `late dynamic pointlist = [];`  It`s work well.

**Comment by zhangruiyu** [comment]
现在支持了
