### ISSUE TITLE
有没有像json_serializable一样的导入方式

### ISSUE THREAD

**Issue by Dboy233** [fluttercandies/FlutterJsonBeanFactory#146]
### Content

FlutterJsonBeanFactory 是 AS 的插件，但是，对于不是 Android 开发的人来说，他们更喜欢使用 vscode，vscode 没有FlutterJsonBeanFactory 这样的插件，可否将FlutterJsonBeanFactory 改造城json_serializable直接集成在项目中，json_serializable生成的bean不如FlutterJsonBeanFactory易用，所以现在为了妥协其他开发还是用了json_serializable。

**Comment by zhangruiyu** [comment]
没办法的  首先我有自己的工作 0-0 这个插件其实也是为了符合我自己的使用搞得 开源出来上架到插件商店也是为了帮助下大家 我并没有那个精力去做其他平台的支持 做这个并没有给我带来任何有用的东西 个人精力确实有限 真的抱歉
而且如果按照json_serializable 那么文件多了就会很慢
