### ISSUE TITLE
[How to use] 自动生成失败

### ISSUE THREAD

**Issue by JohnGuSir** [fluttercandies/FlutterJsonBeanFactory#152]
### Platforms

dart

### Description

No classes that inherit JsonConvert werefound,the project root directory must contain thelib directory, because this plugin will only scanthe lib directory of the root directory

<img width="355" alt="image" src="https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/75824046/15108687-c3fc-455c-822f-4a338ef7249e">

创建文件时，没有自动生成对应的文件，怎么回事啊？

### My code

<img width="815" alt="image" src="https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/75824046/840126ea-3aa0-44d2-b8c0-49727b71b8aa">

<img width="268" alt="image" src="https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/75824046/ff5cc52c-6395-4104-92cd-8dacf4606fd6">

没有自动生成，我需要配置什么吗？

### Try do it

option + J 
弹出 No classes that inherit JsonConvert werefound,the project root directory must contain thelib directory, because this plugin will only scanthe lib directory of the root directory 
窗口

**Comment by zhangruiyu** [comment]
If "No classes that inherit JsonConvert were found" is displayed, delete the ". Idea "directory under the project and click" invalidate Caches"in your (Andorid Studio or IDEA) button to restart the IDE

**Comment by JohnGuSir** [comment]
Thank you
