### ISSUE TITLE
[Feature request] 

### ISSUE THREAD

**Issue by zhonglinhong** [fluttercandies/FlutterJsonBeanFactory#153]
### Platforms

dart

### Description

json_annotation和FlutterJsonBeanFactory同时使用存在问题，建议GeneratorDartClassNodeToHelperInfo中的条件修改为以下判断

        //不包含JsonConvert 那么就不转
        return if (file.text.contains("@JsonSerializable") &&
            !file.text.contains("import 'package:json_annotation/json_annotation.dart';") &&
            file.name != "json_convert_content.dart"
        ) 

### Why

如果项目中包含使用json_annotation插件生成实体的类，使用当前插件生成时也会同时给使用json_annotation插件的类生成.g文件

**Comment by zhangruiyu** [comment]
为啥会混用啊

**Comment by zhonglinhong** [comment]
老项目，改动起来工作量很大

**Comment by zhangruiyu** [comment]
我会考虑加上这个的，我建议加下qq群，然后更新了我可以私聊你jar包

**Comment by zhonglinhong** [comment]
好的，感谢

**Comment by NicolasKim** [comment]
伟大的作者，我们在使用您写的插件的过程中，遇到一个痛点。
团队合作过程中，每位开发者的FlutterJsonBeanFactory版本不一致，导致转换json的代码也有差异，MQ的时候经常会有冲突。
所以我希望提交代码的时候将自动生成的代码忽略掉（加入.gitignore中），使用CI构建时，通过build runner或者某种命令生成转换的代码。这样的话可以避免团队合作过程中代码冲突的问题。也保证了您写的插件可以更丝滑地使用，让你更伟大。

**Comment by zhangruiyu** [comment]
> 伟大的作者，我们在使用您写的插件的过程中，遇到一个痛点。 团队合作过程中，每位开发者的FlutterJsonBeanFactory版本不一致，导致转换json的代码也有差异，MQ的时候经常会有冲突。 所以我希望提交代码的时候将自动生成的代码忽略掉（加入.gitignore中），使用CI构建时，通过build runner或者某种命令生成转换的代码。这样的话可以避免团队合作过程中代码冲突的问题。也保证了您写的插件可以更丝滑地使用，让你更伟大。

加入.gitignore自己就添加了,目前插件必须依赖ide系列的,所以无法通过build runner进行生成
