### ISSUE TITLE
[Bug report] 5.1.2版本在解析list的时候会报错Map<dynamic,dynamic>Not subtype of Map<String, dynamic>

### ISSUE THREAD

**Issue by MMMMiller** [fluttercandies/FlutterJsonBeanFactory#154]
### Version

5.1.2

### Platforms

dart

### Device Model

all

### flutter info

```sh
Flutter 3.13.9 • channel stable 
Engine • revision 0545f8705d
Tools • Dart 3.1.5 • DevTools 2.25.0
[✓] Android Studio (version 2023.1)
```

### How to reproduce?

用json`{"dataList":[{"name":"name1","age":18},{"name":"name2","age":19}]}` 创建entity，
然后用entity.fromJson() ，解析上面这段json， 会报Map<dynamic,dynamic>Not subtype of Map<String, dynamic>。
5.1.1版本正常， 报错位置
![Snipaste_2023-12-07_16-27-03](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/16473252/37592980-7161-406d-86eb-b81d14352eec)

**Comment by zhangruiyu** [comment]
好的 我会尽快修复 麻烦先收到改下吧

**Comment by zhangruiyu** [comment]
好的 我会尽快修复 麻烦先手动改下吧

**Comment by zhangruiyu** [comment]
我觉得你加群私聊我合适 我没复现

**Comment by zhangruiyu** [comment]
qq群963752388
