### ISSUE TITLE
如何脚本自动化运行

### ISSUE THREAD

**Issue by rcj60560** [fluttercandies/FlutterJsonBeanFactory#155]
### Content

目前来看智能在android studio里面去点击Build->FlutterBeanFactory来运行
是不是可以通过脚本语言来执行这个？
比方说再build.gradle里面写个方法
@WangYng @CaiJingLong @AlexV525 @

**Comment by zhangruiyu** [comment]
没法的  这个东西依赖于jb系列的开发工具 脱离了就不行了
