### ISSUE TITLE
No classes that inherit JsonConvert were found,the project root directory must contain the lib directory, because this plugin will only scan the lib directory of the root director

### ISSUE THREAD

**Issue by lgGuo** [fluttercandies/FlutterJsonBeanFactory#160]
### Version

5.1.3

### Platforms

dart, Android

### Device Model

android studio

### flutter info

```sh
[✓] Flutter (Channel stable, 3.3.10, on macOS 14.2.1 23C71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 3.3.10 on channel stable at /Users/flutter_sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (1 year, 3 months ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn
```

### How to reproduce?

删除.idea然后重启也不行，经反复测试十几个版本后，发现 4.2.0可以正常使用，4.3以上都无法正常使用

**Comment by zhangruiyu** [comment]
新建项目可以吗

**Comment by lgGuo** [comment]
> 新建项目可以吗

不行（使用的 Android Studio Iguana | 2023.2.1）

**Comment by lgGuo** [comment]
> 新建项目可以吗

其他同事的也不行

**Comment by zhangruiyu** [comment]
![image](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/10591822/0f46bc50-6d62-4fcd-8c4a-efc9ccdf458d)
![image](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/10591822/6ccf5f89-9228-4379-a57e-1677b13cd7a8)
我测试了下是可以的

**Comment by zhangruiyu** [comment]
![image](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/10591822/9d0ba38e-16b4-4bc3-a4e6-ced24a3fc936)

**Comment by lgGuo** [comment]
> ![image](https://private-user-images.githubusercontent.com/10591822/309694974-0f46bc50-6d62-4fcd-8c4a-efc9ccdf458d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDM2MDMsIm5iZiI6MTcwOTU0MzMwMywicGF0aCI6Ii8xMDU5MTgyMi8zMDk2OTQ5NzQtMGY0NmJjNTAtNmQ2Mi00ZmNkLThjNGEtZWZjOWNjZGY0NThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiODRiZTI3NTZjNDA1N2E2MTVkNWQxZTA3NDFjN2RjM2U1Y2E5NjVlOTMxMTJlYmU3YzM0M2ZmMmY4YTE2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8qaE_Oj2GIuyL6phWCBkTy8qNSIKe3fnzgvuSu-Xo8) ![image](https://private-user-images.githubusercontent.com/10591822/309695013-6ccf5f89-9228-4379-a57e-1677b13cd7a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDM2MDMsIm5iZiI6MTcwOTU0MzMwMywicGF0aCI6Ii8xMDU5MTgyMi8zMDk2OTUwMTMtNmNjZjVmODktOTIyOC00Mzc5LWE1N2UtMTY3N2IxM2NkN2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2NlZDQwZWY3M2RmZjdmNzFiYmU1MDIxNmUzOGNmYjlhMzRjZmU1NDM4Mzk0OTlhZDExZDRhNmUzMjRjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gngmGVG_1pHY7OVTMkgwVIZO-xF4_Gc1XQ5kL4g7y2M) 我测试了下是可以的

5.1.3使用方式是注解这种吗？我目前是使用 with JsonConvert 这种方式
![image](https://github.com/fluttercandies/FlutterJsonBeanFactory/assets/13808932/041c3db4-802b-4157-b8c5-5dfea712762b)

**Comment by zhangruiyu** [comment]
并不是,很早之前就改成了@JsonSerializable()
你们应该有2年没升级过插件了 之前很久的版本有做个迁移版本 不过我也现在也忘记是哪个版本了

**Comment by lgGuo** [comment]
> > ![image](https://private-user-images.githubusercontent.com/10591822/309694974-0f46bc50-6d62-4fcd-8c4a-efc9ccdf458d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDM2MDMsIm5iZiI6MTcwOTU0MzMwMywicGF0aCI6Ii8xMDU5MTgyMi8zMDk2OTQ5NzQtMGY0NmJjNTAtNmQ2Mi00ZmNkLThjNGEtZWZjOWNjZGY0NThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiODRiZTI3NTZjNDA1N2E2MTVkNWQxZTA3NDFjN2RjM2U1Y2E5NjVlOTMxMTJlYmU3YzM0M2ZmMmY4YTE2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8qaE_Oj2GIuyL6phWCBkTy8qNSIKe3fnzgvuSu-Xo8) ![image](https://private-user-images.githubusercontent.com/10591822/309695013-6ccf5f89-9228-4379-a57e-1677b13cd7a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDM2MDMsIm5iZiI6MTcwOTU0MzMwMywicGF0aCI6Ii8xMDU5MTgyMi8zMDk2OTUwMTMtNmNjZjVmODktOTIyOC00Mzc5LWE1N2UtMTY3N2IxM2NkN2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5MDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2NlZDQwZWY3M2RmZjdmNzFiYmU1MDIxNmUzOGNmYjlhMzRjZmU1NDM4Mzk0OTlhZDExZDRhNmUzMjRjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gngmGVG_1pHY7OVTMkgwVIZO-xF4_Gc1XQ5kL4g7y2M) 我测试了下是可以的
> 
> 5.1.3使用方式是注解这种吗？我目前是使用 with JsonConvert 这种方式 ![image](https://private-user-images.githubusercontent.com/13808932/309697804-041c3db4-802b-4157-b8c5-5dfea712762b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDQxNDcsIm5iZiI6MTcwOTU0Mzg0NywicGF0aCI6Ii8xMzgwODkzMi8zMDk2OTc4MDQtMDQxYzNkYjQtODAyYi00MTU3LWI4YzUtNWRmZWE3MTI3NjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5MTcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NzU3ZmZiZjc1M2RhNTVmZTM1M2Y0MjJjYWNhNmI4MTlkNjNjYTE1NjMwZGMxYzU0YzdjOTY3YmFjYzVkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4XfESEDpylqfe0vFchjCLLevIYKEo_J_5Cuoy_TwlE)

为啥你这生成的.g文件

> 并不是,很早之前就改成了@JsonSerializable() 你们应该有2年没升级过插件了 之前很久的版本有做个迁移版本 不过我也现在也忘记是哪个版本了

迁移过后的是生成.g,不是之前的 helper是吗？那估计就是这个问题，这个插件一直没升过，一直在用 4.2这版

**Comment by zhangruiyu** [comment]
嗯 那看你自己了 升级就是新的

**Comment by lgGuo** [comment]
> 嗯 那看你自己了 升级就是新的

好的，感谢
