### ISSUE TITLE
能否不要每次生成的时候，将lib/generator中的内容全部重置

### ISSUE THREAD

**Issue by zkqueen** [fluttercandies/FlutterJsonBeanFactory#171]
### Platforms

dart

### Description

两个问题：
1. 能否生成代码的时候，不要扫描所有的jsonSerilized的注解，仅处理我新生成的代码，太多的change不太适合，大团队的开发 
2. 生成代码的位置，能否可以支持 在当前路径下 ，比如 test/a.dart 为json Model ，生成代码位置保持不变 test/a.g.dart 
还有如果有需要内推，可以联系我 1259183297@qq.com

### Why

1. 不覆盖已有代码
2. 生成在原地

**Comment by zhangruiyu** [comment]
1.按道理可以的 本地做下上次生成时间,然后去判断文件最后改动时间
2.这个不支持的,放在统计目录下 太乱了 而且不利于去封装导包 目前能用的情况下 改动太大了 而且官方的宏可能要出了 
 
最后感谢内推,目前已经入职了 插件没有更新 所有没去掉这个

**Comment by zkqueen** [comment]
我们还是同一个群的呢 ，大佬 fluttercandies 有没有我说的这个效果的插件 推荐下 ，还有官方的宏，可以给我个链接么 我提前了解下

**Comment by zhangruiyu** [comment]
freezed吧 
官方的宏 没出正式版呢

**Comment by tanzhihao1qaz** [comment]
> 1.按道理可以的 本地做下上次生成时间,然后去判断文件最后改动时间 2.这个不支持的,放在同级目录下 太乱了 而且不利于去封装导包 目前能用的情况下 改动太大了 而且官方的宏可能要出了
> 
> 最后感谢内推,目前已经入职了 插件没有更新 所有没去掉这个

"本地做下上次生成时间"这个是如何操作？
