### ISSUE TITLE
The file has too many nested expressions or statements

### ISSUE THREAD

**Issue by JianYiLead** [fluttercandies/FlutterJsonBeanFactory#90]
model多了之后，if-else过多，导致无法使用，报错如下：
lib/generated/json/base/json_convert_content.dart:3828:4: Error: The file has too many nested expressions or statements.
lib/generated/json/base/json_convert_content.dart:3829:10: Error: The file has too many nested expressions or statements.
lib/generated/json/base/json_convert_content.dart:5104:4: Error: The file has too many nested expressions or statements.
lib/generated/json/base/json_convert_content.dart:5105:10: Error: The file has too many nested expressions or statements.

**Comment by zhangruiyu** [comment]
加群聊吧

**Comment by zhangruiyu** [comment]
新版本已修复
