### ISSUE TITLE
support for 2021.2

### ISSUE THREAD

**Issue by limebinary** [fluttercandies/FlutterJsonBeanFactory#96]
Hi, IDEA has released new version 2021.2 recently. Now It shows FlutterJsonBeanFactory is incompatible. Hope update soon. Thanks a lot!

**Comment by zhangruiyu** [comment]
Very soon. I'm probably expecting to finish by 5pm

**Comment by zhangruiyu** [comment]
https://plugins.jetbrains.com/plugin/11415-flutterjsonbeanfactory/versions
version 4.1.7 has been released

**Comment by limebinary** [comment]
WOW! So quick! Thanks
